---
# Copyright 2016, Rackspace US, Inc.
#
# (C) 2016 Michael Rice <michael.rice@rackspace.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install cloudkitty packages (venv)
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ cloudkitty_venv_dir }}"
    virtualenv_site_packages: "no"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ cloudkitty_pip_packages }}"
  when:
    - cloudkitty_venv_enabled | bool
  notify:
    - Restart cloudkitty api
  tags:
    - cloudkitty-install
    - cloudkitty-install-pip-packages

- name: Install cloudkitty pip packages (no venv)
  pip:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ cloudkitty_pip_packages }}"
  when:
    - not cloudkitty_venv_enabled | bool
  notify:
    - Restart cloudkitty api
  tags:
    - cloudkitty-install
    - cloudkitty-install-pip-packages
